#!/bin/bash

read -p "Resource Group: " rg
read -p "VNet Name: " vnet

rg=$(echo $rg | sed 's/"//g')
vnet=$(echo $vnet | sed 's/"//g')

/usr/local/bin/az network vnet list-available-ips -g $rg -n $vnet
