#!/bin/sh

. ~/azure/conf

names=$(/usr/local/bin/az resource list | jq '.[].name' | sort -u)

for n in ${names[*]}
do
	echo "${cyan}Resource Name: $n${reset}"
done

read -p "Choose a resource name: " rn

name=$(echo $rn | sed 's/"//g')
echo "${yellow}az resource list --name $name${reset}"
/usr/local/bin/az resource list --name "$name"

