#!/bin/sh

. ~/azure/conf

names=$(az resource list | jq '.[].name' | sort -u)

for n in ${names[*]}
do
	echo "${cyan}Resource Name: $n${reset}"
done

read -p "Choose a resource name: " rn

name=$(echo $rn | sed 's/"//g')
echo "${yellow}az resource list --name $name${reset}"
az resource list --name "$name"

