---
- name: sample
  hosts: localhost
  become: no
  vars:
    script: kv.py
    kv: kv-box-001
  tasks:
    - name: get all kv secrets
      shell: "./kv.py -k {{ kv }} -s helloworld test-001"
      register: out

    - name: set name value hash
      set_fact:
        ss: "{{ ss|default({}) | combine({ item.name:item.value }) }}"
      with_items:
        - "{{ out.stdout }}"

    - name: display ss hash
      debug:
        msg: "{{ item }}"
      with_items:
        - "{{ ss }}"

    - name: display ss value
      debug:
        msg: "{{ ss['helloworld'] }}"


