---
- name: sample
  hosts: localhost
  become: no
  vars:
    script: kv-s.py
  tasks:
    - name: get all kv secrets
      script: "{{ script }} all"
      register: out

    - name: display all screts
      debug:
        msg: "{{ item.name }} => {{ item.value }}"
      with_items:
        - "{{ out.stdout }}"

    - name: set name value hash
      set_fact:
        ss: "{{ ss|default({}) | combine({ item.name:item.value }) }}"
      with_items:
        - "{{ out.stdout }}"

    - name: display ss hash
      debug:
        msg: "{{ item }}"
      with_items:
        - "{{ ss }}"

    - name: display ss value
      debug:
        msg: "{{ ss['helloworld'] }}"


